---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  apt:
    name: ntp
    update_cache: true
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
